% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Projeto Google Capstone: Estudo de caso 2 - Como um compartilhamento de bicicletas alcança o sucesso rápido?},
  pdfauthor={Luis Gustavo Cezar Puga},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Projeto Google Capstone: Estudo de caso 2 - Como um
compartilhamento de bicicletas alcança o sucesso rápido?}
\author{Luis Gustavo Cezar Puga}
\date{}

\begin{document}
\maketitle

\hypertarget{sobre-uma-empresa}{%
\section{Sobre uma empresa}\label{sobre-uma-empresa}}

Bellabeat, uma fabricante de alta tecnologia de produtos voltados para a
saúde das mulheres. É uma pequena empresa de sucesso, mas com um grande
potencial para expansão, principalmente no cenário global de
dispositivos inteligentes. Urška Sršen, cofundadora e diretora decriação
da Bellabeat, acredita que a análise de dados de condicionamento físico
de dispositivos inteligentes pode ajudar a desbloquear um novo
crescimento de oportunidades para a empresa. A tecnologia Bellabeat
ajuda a capacitar mulheres com conhecimento sobre sua própria saúde e
hábitos.

\hypertarget{perguntas-para-a-anuxe1lise}{%
\section{Perguntas para a análise}\label{perguntas-para-a-anuxe1lise}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Quais são as tendências no uso de dispositivos inteligentes?
\item
  Como estas tendências podem se aplicar aos clientes da Bellabeat?
\item
  Como essas tendências podem ajudar a influenciar a estratégia de
  marketing da Bellabeat
\end{enumerate}

\hypertarget{tarefa-de-neguxf3cios}{%
\section{Tarefa de negócios}\label{tarefa-de-neguxf3cios}}

Identificar potenciais oportunidades de crescimento e recomendações para
o Melhoria da estratégia de marketing Bellabeat com base nas tendências
em dispositivos inteligentes uso.

\hypertarget{fonte-de-dados}{%
\section{Fonte de Dados}\label{fonte-de-dados}}

\begin{itemize}
\item
  Kaggle: FitBit Fitness Tracker Data
  (\url{https://www.kaggle.com/datasets/arashnic/fitbit})
\item
  Kernel(s) Inicial(is): Anastasiia Chebotina:
  \url{https://www.kaggle.com/chebotinaa/bellabeat-case-study-with-r}\\
  Julen Aranguren:
  \url{https://www.kaggle.com/code/foxsjl/bellabeat-product-analysis-a-capstone-project}\\
\item
  Reconhecimento:\\
  Index of bucket ``divvy-tripdata''
  \url{https://divvy-tripdata.s3.amazonaws.com/index.html}
\end{itemize}

\hypertarget{carregando-pacotes-e-diretuxf3rio-de-trabalho}{%
\section{Carregando pacotes e diretório de
trabalho}\label{carregando-pacotes-e-diretuxf3rio-de-trabalho}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#setwd("/home/gustavo/Projetos/R/cyclistic{-}bike{-}share{-}a{-}case{-}study")}
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching packages --------------------------------------- tidyverse 1.3.2 --
## v ggplot2 3.4.0      v purrr   0.3.5 
## v tibble  3.1.8      v dplyr   1.0.10
## v tidyr   1.2.1      v stringr 1.5.0 
## v readr   2.1.3      v forcats 0.5.2 
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(skimr)}
\end{Highlighting}
\end{Shaded}

\hypertarget{importing-datasets}{%
\section{Importing datasets}\label{importing-datasets}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{activity }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"Data/Activity\_Daily.csv"}\NormalTok{)}
\NormalTok{calories }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"Data/Calories\_Hourly.csv"}\NormalTok{)}
\NormalTok{intensities }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"Data/Intensities\_Hourly.csv"}\NormalTok{)}
\NormalTok{sleep }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"Data/Sleep\_Day.csv"}\NormalTok{)}
\NormalTok{weight }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"Data/Weight\_Log\_Info.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Já verifiquei os dados no Libre Office. Eu só preciso ter certeza que
tudo foi importado corretamente usando View() e head() funções.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(activity)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           Id ActivityDate TotalSteps TotalDistance TrackerDistance
## 1 1503960366    4/12/2016      13162          8.50            8.50
## 2 1503960366    4/13/2016      10735          6.97            6.97
## 3 1503960366    4/14/2016      10460          6.74            6.74
## 4 1503960366    4/15/2016       9762          6.28            6.28
## 5 1503960366    4/16/2016      12669          8.16            8.16
## 6 1503960366    4/17/2016       9705          6.48            6.48
##   LoggedActivitiesDistance VeryActiveDistance ModeratelyActiveDistance
## 1                        0               1.88                     0.55
## 2                        0               1.57                     0.69
## 3                        0               2.44                     0.40
## 4                        0               2.14                     1.26
## 5                        0               2.71                     0.41
## 6                        0               3.19                     0.78
##   LightActiveDistance SedentaryActiveDistance VeryActiveMinutes
## 1                6.06                       0                25
## 2                4.71                       0                21
## 3                3.91                       0                30
## 4                2.83                       0                29
## 5                5.04                       0                36
## 6                2.51                       0                38
##   FairlyActiveMinutes LightlyActiveMinutes SedentaryMinutes Calories
## 1                  13                  328              728     1985
## 2                  19                  217              776     1797
## 3                  11                  181             1218     1776
## 4                  34                  209              726     1745
## 5                  10                  221              773     1863
## 6                  20                  164              539     1728
\end{verbatim}

Identifiquei alguns problemas com os dados do \emph{timestamp} de
data/hora. Então, antes da análise, preciso convertê-los para o formato
\emph{data-hora} e dividir em data e hora.

\hypertarget{corrigindo-a-formatauxe7uxe3o}{%
\section{Corrigindo a formatação}\label{corrigindo-a-formatauxe7uxe3o}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# intensities}
\NormalTok{intensities}\SpecialCharTok{$}\NormalTok{ActivityHour}\OtherTok{=}\FunctionTok{as.POSIXct}\NormalTok{(intensities}\SpecialCharTok{$}\NormalTok{ActivityHour, }\AttributeTok{format=}\StringTok{"\%m/\%d/\%Y \%I:\%M:\%S \%p"}\NormalTok{, }\AttributeTok{tz=}\FunctionTok{Sys.timezone}\NormalTok{())}
\NormalTok{intensities}\SpecialCharTok{$}\NormalTok{time }\OtherTok{\textless{}{-}} \FunctionTok{format}\NormalTok{(intensities}\SpecialCharTok{$}\NormalTok{ActivityHour, }\AttributeTok{format =} \StringTok{"\%H:\%M:\%S"}\NormalTok{)}
\NormalTok{intensities}\SpecialCharTok{$}\NormalTok{date }\OtherTok{\textless{}{-}} \FunctionTok{format}\NormalTok{(intensities}\SpecialCharTok{$}\NormalTok{ActivityHour, }\AttributeTok{format =} \StringTok{"\%m/\%d/\%y"}\NormalTok{)}
\CommentTok{\# calories}
\NormalTok{calories}\SpecialCharTok{$}\NormalTok{ActivityHour}\OtherTok{=}\FunctionTok{as.POSIXct}\NormalTok{(calories}\SpecialCharTok{$}\NormalTok{ActivityHour, }\AttributeTok{format=}\StringTok{"\%m/\%d/\%Y \%I:\%M:\%S \%p"}\NormalTok{, }\AttributeTok{tz=}\FunctionTok{Sys.timezone}\NormalTok{())}
\NormalTok{calories}\SpecialCharTok{$}\NormalTok{time }\OtherTok{\textless{}{-}} \FunctionTok{format}\NormalTok{(calories}\SpecialCharTok{$}\NormalTok{ActivityHour, }\AttributeTok{format =} \StringTok{"\%H:\%M:\%S"}\NormalTok{)}
\NormalTok{calories}\SpecialCharTok{$}\NormalTok{date }\OtherTok{\textless{}{-}} \FunctionTok{format}\NormalTok{(calories}\SpecialCharTok{$}\NormalTok{ActivityHour, }\AttributeTok{format =} \StringTok{"\%m/\%d/\%y"}\NormalTok{)}
\CommentTok{\# activity}
\NormalTok{activity}\SpecialCharTok{$}\NormalTok{ActivityDate}\OtherTok{=}\FunctionTok{as.POSIXct}\NormalTok{(activity}\SpecialCharTok{$}\NormalTok{ActivityDate, }\AttributeTok{format=}\StringTok{"\%m/\%d/\%Y"}\NormalTok{, }\AttributeTok{tz=}\FunctionTok{Sys.timezone}\NormalTok{())}
\NormalTok{activity}\SpecialCharTok{$}\NormalTok{date }\OtherTok{\textless{}{-}} \FunctionTok{format}\NormalTok{(activity}\SpecialCharTok{$}\NormalTok{ActivityDate, }\AttributeTok{format =} \StringTok{"\%m/\%d/\%y"}\NormalTok{)}
\CommentTok{\# sleep}
\NormalTok{sleep}\SpecialCharTok{$}\NormalTok{SleepDay}\OtherTok{=}\FunctionTok{as.POSIXct}\NormalTok{(sleep}\SpecialCharTok{$}\NormalTok{SleepDay, }\AttributeTok{format=}\StringTok{"\%m/\%d/\%Y \%I:\%M:\%S \%p"}\NormalTok{, }\AttributeTok{tz=}\FunctionTok{Sys.timezone}\NormalTok{())}
\NormalTok{sleep}\SpecialCharTok{$}\NormalTok{date }\OtherTok{\textless{}{-}} \FunctionTok{format}\NormalTok{(sleep}\SpecialCharTok{$}\NormalTok{SleepDay, }\AttributeTok{format =} \StringTok{"\%m/\%d/\%y"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Agora que tudo está pronto, posso começar a explorar os conjuntos de
dados.

\hypertarget{explorando-e-resumindo-dados}{%
\section{Explorando e resumindo
dados}\label{explorando-e-resumindo-dados}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{n\_distinct}\NormalTok{(activity}\SpecialCharTok{$}\NormalTok{Id)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 33
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{n\_distinct}\NormalTok{(calories}\SpecialCharTok{$}\NormalTok{Id)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 33
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{n\_distinct}\NormalTok{(intensities}\SpecialCharTok{$}\NormalTok{Id)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 33
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{n\_distinct}\NormalTok{(sleep}\SpecialCharTok{$}\NormalTok{Id)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 24
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{n\_distinct}\NormalTok{(weight}\SpecialCharTok{$}\NormalTok{Id)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 8
\end{verbatim}

Esta informação nos alerta sobre o número de participantes em cada
conjunto de dados.

Há 33 participantes nos dados de atividade, calorias e intensidades
conjuntos, 24 no sono e apenas 8 no conjunto de dados de peso. 8
participantes não é significativo fazer recomendações e conclusões com
base em esses dados.

Vamos dar uma olhada nas estatísticas resumidas dos conjuntos de dados:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# activity}
\NormalTok{activity }\SpecialCharTok{\%\textgreater{}\%}  
  \FunctionTok{select}\NormalTok{(TotalSteps,}
\NormalTok{         TotalDistance,}
\NormalTok{         SedentaryMinutes, Calories) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summary}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    TotalSteps    TotalDistance    SedentaryMinutes    Calories   
##  Min.   :    0   Min.   : 0.000   Min.   :   0.0   Min.   :   0  
##  1st Qu.: 3790   1st Qu.: 2.620   1st Qu.: 729.8   1st Qu.:1828  
##  Median : 7406   Median : 5.245   Median :1057.5   Median :2134  
##  Mean   : 7638   Mean   : 5.490   Mean   : 991.2   Mean   :2304  
##  3rd Qu.:10727   3rd Qu.: 7.713   3rd Qu.:1229.5   3rd Qu.:2793  
##  Max.   :36019   Max.   :28.030   Max.   :1440.0   Max.   :4900
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\StringTok{"\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "___________________________________________________________"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# explore num of active minutes per category}
\NormalTok{activity }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(VeryActiveMinutes, FairlyActiveMinutes, LightlyActiveMinutes) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summary}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  VeryActiveMinutes FairlyActiveMinutes LightlyActiveMinutes
##  Min.   :  0.00    Min.   :  0.00      Min.   :  0.0       
##  1st Qu.:  0.00    1st Qu.:  0.00      1st Qu.:127.0       
##  Median :  4.00    Median :  6.00      Median :199.0       
##  Mean   : 21.16    Mean   : 13.56      Mean   :192.8       
##  3rd Qu.: 32.00    3rd Qu.: 19.00      3rd Qu.:264.0       
##  Max.   :210.00    Max.   :143.00      Max.   :518.0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\StringTok{"\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "___________________________________________________________"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# calories}
\NormalTok{calories }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(Calories) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summary}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     Calories     
##  Min.   : 42.00  
##  1st Qu.: 63.00  
##  Median : 83.00  
##  Mean   : 97.39  
##  3rd Qu.:108.00  
##  Max.   :948.00
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\StringTok{"\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "___________________________________________________________"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# sleep}
\NormalTok{sleep }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(TotalSleepRecords, TotalMinutesAsleep, TotalTimeInBed) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summary}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  TotalSleepRecords TotalMinutesAsleep TotalTimeInBed 
##  Min.   :1.000     Min.   : 58.0      Min.   : 61.0  
##  1st Qu.:1.000     1st Qu.:361.0      1st Qu.:403.0  
##  Median :1.000     Median :433.0      Median :463.0  
##  Mean   :1.119     Mean   :419.5      Mean   :458.6  
##  3rd Qu.:1.000     3rd Qu.:490.0      3rd Qu.:526.0  
##  Max.   :3.000     Max.   :796.0      Max.   :961.0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\StringTok{"\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "___________________________________________________________"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# weight}
\NormalTok{weight }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(WeightKg, BMI) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summary}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     WeightKg           BMI       
##  Min.   : 52.60   Min.   :21.45  
##  1st Qu.: 61.40   1st Qu.:23.96  
##  Median : 62.50   Median :24.39  
##  Mean   : 72.04   Mean   :25.19  
##  3rd Qu.: 85.05   3rd Qu.:25.56  
##  Max.   :133.50   Max.   :47.54
\end{verbatim}

\textbf{Algumas descobertas interessantes deste resumo:}

\begin{itemize}
\item
  O tempo médio sedentário é de 991 minutos ou 16 horas. definitivamente
  precisa ser reduzido!
\item
  A maioria dos participantes é levemente ativa.
\item
  Em média, os participantes dormem 1 vez por 7 horas.
\item
  O total médio de passos por dia é de 7638, um pouco menos para tendo
  benefícios para a saúde de acordo com a pesquisa do CDC. Eles
  encontraram que dar 8.000 passos por dia foi associado a um risco 51\%
  menor para todas as causas de mortalidade (ou morte por todas as
  causas). Levando 12.000 passos por dia foi associado a um risco 65\%
  menor em comparação com dando 4.000 passos.
\end{itemize}

\hypertarget{mesclando-dados}{%
\section{Mesclando dados}\label{mesclando-dados}}

Antes de começar a visualizar os dados, eu preciso fundir dois conjuntos
de dados. Vou fundir (união interna) '' activity'' e ``sleep'' nas
colunas id e date (que eu criei anteriormente após converter os dados
para o formato de data e hora).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{merged\_data }\OtherTok{\textless{}{-}} \FunctionTok{merge}\NormalTok{(sleep, activity, }\AttributeTok{by=}\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}Id\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}date\textquotesingle{}}\NormalTok{))}
\FunctionTok{head}\NormalTok{(merged\_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           Id     date   SleepDay TotalSleepRecords TotalMinutesAsleep
## 1 1503960366 04/12/16 2016-04-12                 1                327
## 2 1503960366 04/13/16 2016-04-13                 2                384
## 3 1503960366 04/15/16 2016-04-15                 1                412
## 4 1503960366 04/16/16 2016-04-16                 2                340
## 5 1503960366 04/17/16 2016-04-17                 1                700
## 6 1503960366 04/19/16 2016-04-19                 1                304
##   TotalTimeInBed ActivityDate TotalSteps TotalDistance TrackerDistance
## 1            346   2016-04-12      13162          8.50            8.50
## 2            407   2016-04-13      10735          6.97            6.97
## 3            442   2016-04-15       9762          6.28            6.28
## 4            367   2016-04-16      12669          8.16            8.16
## 5            712   2016-04-17       9705          6.48            6.48
## 6            320   2016-04-19      15506          9.88            9.88
##   LoggedActivitiesDistance VeryActiveDistance ModeratelyActiveDistance
## 1                        0               1.88                     0.55
## 2                        0               1.57                     0.69
## 3                        0               2.14                     1.26
## 4                        0               2.71                     0.41
## 5                        0               3.19                     0.78
## 6                        0               3.53                     1.32
##   LightActiveDistance SedentaryActiveDistance VeryActiveMinutes
## 1                6.06                       0                25
## 2                4.71                       0                21
## 3                2.83                       0                29
## 4                5.04                       0                36
## 5                2.51                       0                38
## 6                5.03                       0                50
##   FairlyActiveMinutes LightlyActiveMinutes SedentaryMinutes Calories
## 1                  13                  328              728     1985
## 2                  19                  217              776     1797
## 3                  34                  209              726     1745
## 4                  10                  221              773     1863
## 5                  20                  164              539     1728
## 6                  31                  264              775     2035
\end{verbatim}

\hypertarget{visualizauxe7uxe3o}{%
\section{Visualização}\label{visualizauxe7uxe3o}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data=}\NormalTok{activity, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{TotalSteps, }\AttributeTok{y=}\NormalTok{Calories)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_jitter}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{geom\_smooth}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{"Total Steps vs. Calories"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using method = 'loess' and formula = 'y ~ x'
\end{verbatim}

\includegraphics{V2-My-Assement{[}por{]}_files/figure-latex/unnamed-chunk-8-1.pdf}

Vejo aqui uma correlação positiva entre ``Total Steps'' e ``Calories'',
o que é uma causalidade, pois quanto mais ativos passos damos, mais
calorias queimamos.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data=}\NormalTok{sleep, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{TotalMinutesAsleep, }\AttributeTok{y=}\NormalTok{TotalTimeInBed)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_point}\NormalTok{()}\SpecialCharTok{+} \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{"Total Minutes Asleep vs. Total Time in Bed"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{V2-My-Assement{[}por{]}_files/figure-latex/unnamed-chunk-9-1.pdf}

A relação entre ``Total Minutes Asleep'' e ``Total Time in Bed'' parece
linear. Portanto, se os usuários do Bellabeat querem melhorar seu sono,
devemos considerar o uso da notificação para ir dormir.

Vamos olhar para os \textbf{dados de intensidade} ao longo do tempo (de
hora em hora).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{int\_new }\OtherTok{\textless{}{-}}\NormalTok{ intensities }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(time) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{drop\_na}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{mean\_total\_int =} \FunctionTok{mean}\NormalTok{(TotalIntensity))}

\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data=}\NormalTok{int\_new, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{time, }\AttributeTok{y=}\NormalTok{mean\_total\_int)) }\SpecialCharTok{+} \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{, }\AttributeTok{fill=}\StringTok{\textquotesingle{}darkblue\textquotesingle{}}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{"Average Total Intensity vs. Time"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in geom_histogram(stat = "identity", fill = "darkblue"): Ignoring
## unknown parameters: `binwidth`, `bins`, and `pad`
\end{verbatim}

\includegraphics{V2-My-Assement{[}por{]}_files/figure-latex/unnamed-chunk-10-1.pdf}

\begin{itemize}
\item
  Depois de visualizar ``Intensidade Total por hora'', descobri que as
  pessoas são mais ativas entre 5 da manhã e 10 da noite.
\item
  A maioria das atividades acontece entre 17h e 19h - suponho, que as
  pessoas vão a uma academia de ginástica ou para um passeio depois de
  terminar o trabalho. Podemos usar este tempo no aplicativo Bellabeat
  para lembrar e motivar os usuários a ir correr ou caminhar.
\end{itemize}

Vejamos a relação entre ``Total Minutes Asleep'' e ``Sedentry Minutes''.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data=}\NormalTok{merged\_data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{TotalMinutesAsleep, }\AttributeTok{y=}\NormalTok{SedentaryMinutes)) }\SpecialCharTok{+} 
\FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{color=}\StringTok{\textquotesingle{}darkblue\textquotesingle{}}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{geom\_smooth}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{"Minutes Asleep vs. Sedentary Minutes"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using method = 'loess' and formula = 'y ~ x'
\end{verbatim}

\includegraphics{V2-My-Assement{[}por{]}_files/figure-latex/unnamed-chunk-11-1.pdf}

\begin{itemize}
\item
  Aqui podemos ver claramente a relação negativa entre ``Ata
  Sedentária'' e ``Hora do Sono''.
\item
  Como uma idéia: se os usuários do Bellabeat querem melhorar seu sono,
  Bellabeat app pode recomendar a redução do tempo de sedentarismo.
\item
  Tenha em mente que precisamos apoiar esta percepção com mais dados,
  pois a correlação entre alguns dados não significa causalidade.
\end{itemize}

\hypertarget{resumindo-as-recomendauxe7uxf5es-para-o-neguxf3cio}{%
\section{Resumindo as recomendações para o
negócio}\label{resumindo-as-recomendauxe7uxf5es-para-o-neguxf3cio}}

Como já sabemos, coletar dados sobre atividade, sono, estresse e saúde
reprodutiva permitiu que Bellabeat empoderasse mulheres com conhecimento
sobre sua própria saúde e hábitos. Desde que foi fundado em 2013,
Bellabeat cresceu rapidamente e rapidamente se posicionou como um
empresa de bem-estar voltada para a tecnologia para mulheres.

Depois de analisar os dados do FitBit Fitness Tracker, encontrei alguns
\textbf{insights isso ajudaria a influenciar a estratégia de marketing
da Bellabeat.}

\includegraphics{https://cdn.pixabay.com/photo/2021/07/27/22/18/woman-6497870_960_720.jpg}

\textbf{Público-alvo}

Mulheres que trabalham em tempo integral (de acordo com os dados de
intensidade horária) e passa muito tempo no computador/em reunião/focado
no trabalho estão fazendo (de acordo com os dados de tempo sedentário).

Essas mulheres fazem alguma atividade leve para se manterem saudáveis
(de acordo com o análise do tipo de atividade). Mesmo que eles precisem
melhorar seu cotidiano atividade tenha benefícios para a saúde. Eles
podem precisar de algum conhecimento sobre desenvolver hábitos saudáveis
ou motivação para continuar.

\begin{itemize}
\tightlist
\item
  Como não há informações de gênero sobre os participantes, presumi que
  todos os gêneros foram apresentados e equilibrados neste conjunto de
  dados.
\end{itemize}

\textbf{A principal mensagem da campanha on-line do Bellabeat}

O aplicativo Bellabeat não é apenas mais um aplicativo de atividades
físicas. é um guia (uma amiga) que empodera as mulheres para equilibrar
a vida pessoal e profissional vida e hábitos e rotinas saudáveis,
educando-os e motivando-os por meio de recomendações diárias de
aplicativos.

\textbf{Ideias para o aplicativo Bellabeat}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  O total médio de passos por dia é de 7.638, um pouco menos para tendo
  benefícios para a saúde de acordo com a pesquisa do CDC. Eles
  encontraram que dar 8.000 passos por dia foi associado a um risco 51\%
  menor para todas as causas de mortalidade (ou morte por todas as
  causas). Levando 12.000 passos por dia foi associado a um risco 65\%
  menor em comparação com dando 4.000 passos. Bellabeat pode encorajar
  as pessoas a tomar pelo menos 8 000 explicando os benefícios para a
  sua saúde.
\item
  Se os usuários desejam perder peso, provavelmente é uma boa ideia
  controlar consumo calórico diário. Bellabeat pode sugerir algumas
  ideias para almoço e jantar de baixa caloria.
\item
  Se os usuários quiserem melhorar o sono, o Bellabeat deve considerar
  usando notificações de aplicativos para ir para a cama.
\item
  A maioria das atividades acontece entre 17h e 19h - suponho que as
  pessoas vá a uma academia ou dê um passeio depois de terminar o
  trabalho. Bellabeat pode usar desta vez para lembrar e motivar os
  usuários a correr ou caminhar.
\item
  Uma ideia: se o usuário quiser melhorar o sono, o aplicativo Bellabeat
  pode recomendar a redução do tempo sedentário.
\end{enumerate}

\end{document}
